"""empty message

Revision ID: ddf67324d0f5
Revises: 
Create Date: 2020-12-12 02:49:36.770294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddf67324d0f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emp123')
    op.drop_table('emp')
    op.drop_table('table2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table2',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=True)
    )
    op.create_table('emp',
    sa.Column('empno', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fname', sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.create_table('emp123',
    sa.Column('empno', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fname', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('empno', name='emp123_pkey')
    )
    # ### end Alembic commands ###
